#ifndef DICOMFILEREADER_H
#define DICOMFILEREADER_H

#include <QList>
#include <QString>

#include "vtkMatrix4x4.h"
#include "vtkTransform.h"
#include "vtkImageData.h"
#include "vtkImageChangeInformation.h"
#include "vtkSmartPointer.h"
#include "vtkMatrixToLinearTransform.h"

// DCMTK
#include "cfunix.h"
#include "ofstring.h"

  const int NUM_ENTRIES = 4;
  const std::string ENTRY_STRINGS[NUM_ENTRIES] = {"HFS", "FFS","HFP","FFP"};
  const int ENTRY_FLIPS[NUM_ENTRIES][3] = {
    {1,1,1}, /* Head First Supine to RCS*/
    {-1,1,-1}, /* Feet First Supine to RCS */
    {-1,-1,1}, /* Head First Prone to RCS */
    {1,-1,-1} /* Feet First Prone to RCS */
  };

class DICOMFileReader
{
public:
  DICOMFileReader();
  ~DICOMFileReader();

  struct DICOMImageData {
    OFString patientsName;
    OFString studyDate;
    OFString studyTime;
    OFString patientPosition;
    unsigned short bitsPerPixel;
    unsigned short sine;
    unsigned short numRows;
    unsigned short numCols;
    unsigned long pixelGroupLen;
    short* shortData;
    unsigned long numElements;
    double pixSpace[2];
    double imgPosition[3]; // Position of img.
    double imgOrient[6]; // Direction cosines
    int fov; // FOV is only valid for square datasets.
    double sliceThickness;
  };


  bool setDirectory(QString dirPath);
  bool readFile(QString fName);
  bool createVolume(QList<DICOMImageData>* imgData);

  vtkImageData* getImageData() { return m_infoFix->GetOutput(); }
  vtkTransform* getTransform() { return m_transform; }

  QString getComments() { return m_comments; }

protected:
  QList<QString> m_fileList;
  QList<DICOMImageData> m_imgData;

  //! The vtk pipeline ready version of the image data.
  vtkSmartPointer<vtkImageData> m_vtkImgData;

  //! Matrix for the transform.
  vtkSmartPointer<vtkMatrix4x4> m_matrix;

  //! The object the converts between the vtkMatrix4x4 and the vtkTransform.
  vtkSmartPointer<vtkMatrixToLinearTransform> m_matrixToTransform;

  //! The transform for the data.
  vtkSmartPointer<vtkTransform> m_transform;

  vtkSmartPointer<vtkImageChangeInformation> m_infoFix;

  //! The DICOM IMAGE header.
  DICOMImageData m_ddata;

  //! The output comments generated by the dicom reader about the file(s).
  QString m_comments;
};

#endif // DICOMFILEREADER_H
